GET http://localhost:3000/menu HTTP/1.1

###
GET http://localhost:3000/menu/11 HTTP/1.1

###
POST http://localhost:3000/menu HTTP/1.1
Content-Type: application/json

{
  "id": 11,
    "nombre": "Perro Caliente",
    "tipo": "Comida Rápida",
    "ingredientes": [
      "Pan",
      "Salchicha",
      "Mostaza",
      "Ketchup",
      "Cebolla",
      "Queso Cheddar"
    ],
    "calorias": 350,
    "precio": 5.99,
    "vegetariano": false
}
###
PUT http://localhost:3000/menu/11 HTTP/1.1
Content-Type: application/json

{
  "nombre": "Hamburguesa con Queso",
  "tipo": "Comida Rápida",
  "ingredientes": [
    "Pan",
    "Carne de Res",
    "Queso Cheddar",
    "Lechuga",
    "Tomate",
    "Cebolla",
    "Pepinillos"
  ],
  "calorias": 500,
  "precio": 8.99,
  "vegetariano": false
}

###
DELETE http://localhost:3000/menu/11 HTTP/1.1