GET http://localhost:3000/menu HTTP/1.1

### error: el ID debe ser un número entero
GET http://localhost:3000/menu/S HTTP/1.1

### error: el ID no existe
GET http://localhost:3000/menu/999 HTTP/1.1

### forma correcta
GET http://localhost:3000/menu/1 HTTP/1.1

### error: campo nombre obligatorio
POST http://localhost:3000/menu HTTP/1.1
Content-Type: application/json

{
    "nombre": "",
    "precio": 10.5
}

### error: campo precio debe ser un número positivo
POST http://localhost:3000/menu HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": -5
}

### error: la descripción debe ser un string
POST http://localhost:3000/menu HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": 123
}

### forma correcta
POST http://localhost:3000/menu HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": "Ensalada fresca con vegetales"
}

### error: el ID debe ser un número entero
PUT http://localhost:3000/menu/S HTTP/1.1
Content-Type: application/json

{
    "id": "S",  
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": "Ensalada fresca con vegetales"
}

### error: el ID no existe
PUT http://localhost:3000/menu/999 HTTP/1.1
Content-Type: application/json

{
    "id": 999,
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": "Ensalada fresca con vegetales"
}

### error: campo nombre obligatorio
PUT http://localhost:3000/menu/6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "",
    "precio": 10.5,
    "descripcion": "Ensalada fresca con vegetales"
}
### error: campo precio debe ser un número positivo
PUT http://localhost:3000/menu/6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": -5,
    "descripcion": "Ensalada fresca con vegetales"
}
### error: la descripción debe ser un string
PUT http://localhost:3000/menu/6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": 123
}

### forma correcta
PUT http://localhost:3000/menu/6 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ensalada",
    "precio": 10.5,
    "descripcion": "Ensalada fresca con vegetales"
}

### error: el ID debe ser un número entero
DELETE http://localhost:3000/menu/S HTTP/1.1

### error: el ID no existe
DELETE http://localhost:3000/menu/999 HTTP/1.1

### forma correcta
DELETE http://localhost:3000/menu/6 HTTP/1.1